default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: vitor_colombiano
  password: quero1234
  host: localhost
  port: 5432
  database: gerenciador_mensalidade


development:
  <<: *default
  database: gerenciador_mensalidade
test:
  <<: *default
  database: gerenciador_mensalidade

production:
  <<: *default
  database: gerenciador_mensalidade